# Reference: https://squidfunk.github.io/mkdocs-material/reference/
site_name: SANS HHC Write-Up
site_author: Yao Amebe
theme:
  icon:
    # Material for MkDocs bundles several icon sets:
    # - Material Design (https://materialdesignicons.com/)
    # - FontAwesome (https://fontawesome.com/search?m=free)
    # - Octicons (https://octicons.github.com/)
    # - Simple Icons (https://simpleicons.org/)
    # Below are some suitable logo examples: 
    # logo: fontawesome/regular/snowflake
    # logo: fontawesome/solid/sleigh
    # logo: fontawesome/solid/candy-cane
    logo: fontawesome/solid/tree
  name: material
  favicon: img/misc/favicon.ico
  features:
    - toc.integrate
    - content.code.copy
    - navigation.sections
    #- navigation.instant
    #- navigation.top
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.expand
    #- navigation.top
    #- navigation.prune
    #- toc.follow
  palette:
    # Material for MkDocs supports a light (default) and dark (slate) theme.
    # Each mode supports configurable primary and accent colors.
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # Primary colors:
    # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal,
    # green, light green, lime, yellow, amber, orange, deep orange, brown,
    # grey, blue grey, black, and white.
    # Accent colors:
    # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal,
    # green, light green, lime, yellow, amber, orange, and deep orange.
    # Palette toggle for dark mode (default)
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/prosperamebe
      name: X (Twitter)
    - icon: fontawesome/brands/github
      link: https://github.com/prosmaw
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yao-prosper-amebe/
      name: LinkedIn
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - footnotes
  - def_list
  - toc:
      permalink: ⚓︎
      toc_depth: 2
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
# The 'nav' section defines the content of the sidebar navigation.
- Welcome: 'index.md'
- Objectives:
  - Act 1:
    - Its All About Defang: 'objectives/o1.md'
    - Neighborhood Watch Bypass: 'objectives/o2.md'
    - Santa's Gift-Tracking Service Port Mystery: 'objectives/o3.md'
    - Visual Networking Thinger: 'objectives/o4.md'
    - Visual Firewall Thinger: 'objectives/o5.md'
    - Intro to Nmap: 'objectives/o6.md'
    - Blob Storage Challenge in the Neighborhood: 'objectives/o7.md'
    - Spare Key: 'objectives/o8.md'
    - The Open Door: 'objectives/o9.md'
    - Owner: 'objectives/o10.md'
  - Act 2:
    - Retro Recovery: 'objectives/o11.md'
    - Mail Detective: 'objectives/o12.md'
    - IDORable Bistro: 'objectives/o13.md'
    - Dosis Network Down: 'objectives/o14.md'
    - Rogue Gnome Identity Provider: 'objectives/o15.md'
    - Quantgnome Leap: 'objectives/o16.md'
    - Going in Reverse: 'objectives/o17.md'
  - Act 3:
    - Gnome Tea: 'objectives/o18.md'
    # - Hack-a-Gnome: 'objectives/o19.md'
    - Snowcat RCE & Priv Esc: 'objectives/o20.md'
    - Schrödinger's Scope: 'objectives/o21.md'
    # - Find and Shutdown Frosty's Snowglobe Machine: 'objectives/o22.md'
    - On the Wire: 'objectives/o23.md'
    # - Free Ski: 'objectives/o24.md'

